server.port=8080

app.data.file=${APP_DATA_DIR:./data}/passwords.json
app.users.file=${APP_DATA_DIR:./data}/users.json

logging.level.com.example.passwordmanager=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

spring.jackson.serialization.INDENT_OUTPUT=true
spring.jackson.default-property-inclusion=non_null

app.jwt.secret=${JWT_SECRET:just-simple-over-32-symbols-jwt-secret-cuz-its-not-for-production}
app.jwt.expiration=900000